[tool.poetry]
name = "chirpity-electron"
version = "0.1.0"
description = ""
authors = ["Mattk70 <email@mattkirkland.co.uk>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
